[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
# Flash at 460800 baud (standard ESP32 speed), monitor at 115200 (CLI speed)
runner = "espflash flash --baud 460800 --monitor"

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = { value = "v5.2.3" }
ESP_IDF_LOG_LEVEL = { value = "info" }
ESP_IDF_TOOLS_INSTALL_DIR = { value = "global" }
